CREATE TABLE fact_encounter (
  ENCOUNTER_Id UUID PRIMARY KEY,
  PATIENT UUID NOT NULL,
  STARTDATE TIMESTAMPTZ NOT NULL,
  STOPDATE TIMESTAMPTZ NULL CHECK(STOPDATE >= STARTDATE),
  ORGANIZATION UUID NOT NULL, 
  PROVIDER UUID NOT NULL,
  PAYER UUID  NOT NULL,    
  BASE_ENCOUNTER_COST DECIMAL(10, 2) NOT NULL CHECK (BASE_ENCOUNTER_COST >=0),
  PAYER_COVERAGE DECIMAL(10, 2) NOT NULL CHECK (PAYER_COVERAGE >=0),
  FOREIGN KEY(PATIENT) REFERENCES DimPatient (Id),-- foreign key column -Organization in the encounter.csv table references the id  column in the Organization.csv table
  FOREIGN KEY(ORGANIZATION) REFERENCES DimOrganization (Id),
  FOREIGN KEY (PROVIDER) REFERENCES DimProvider (Id),
  FOREIGN KEY(PAYER) REFERENCES DimPayer (Id)
);

CREATE TABLE fact_Conditions(
  CONDITION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  STARTDATE DATE NULL,
  STOPDATE DATE NULL CHECK(STOPDATE >= STARTDATE), 
  PATIENT UUID,
  ENCOUNTER UUID,
  SYSTEM TEXT NULL,
  CODE TEXT NULL,
  DESCRIPTION TEXT NULL,
  FOREIGN KEY (PATIENT) REFERENCES DimPatient(Id),
  FOREIGN KEY (ENCOUNTER) REFERENCES Fact_encounter (ENCOUNTER_Id),
  UNIQUE (PATIENT, CODE, ENCOUNTER) --natural key
);

-- create dimensional tables
CREATE TABLE DimPatient ( 
  Id UUID PRIMARY KEY, 
  BIRTHDATE DATE NOT NULL,
  DEATHDATE DATE NULL,
  MARITAL_STATUS TEXT NULL CHECK(MARITAL_STATUS  IN ('M','S','D','W')),  --- Create a column called marital_status that stores text. The value may be missing (NULL). If a value is provided, it must be either 'M', 'S', or 'D'
  RACE TEXT NOT NULL,
  EITHNCITY TEXT,
  GENDER TEXT NOT NULL CHECK(GENDER IN('M','F')),
  BIRTHPLACE TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY TEXT NOT NULL,
  STATE TEXT NOT NULL,
  COUNTY TEXT NOT NULL
);


CREATE TABLE DimOrganization (
  Id UUID PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY TEXT NOT NULL,
  STATE TEXT NOT NULL,
  ZIP TEXT NOT NULL

);

CREATE TABLE DimProvider (
  Id UUID PRIMARY KEY,  
  NAME TEXT NOT NULL,
  ORGANIZATION UUID,
  FOREIGN KEY (ORGANIZATION) REFERENCES DimOrganization (Id),
  GENDER TEXT NOT NULL CHECK (GENDER IN ('M', 'F'))
  SPECIALITY TEXT NOT NULL,
  CITY_provider_Organization TEXT NOT NULL,
  STATE_provider_Organization TEXT NOT NULL
);

CREATE TABLE Dimpayer(
  Id UUID PRIMARY KEY,   
  NAME TEXT NULL,
  OWNERSHIP_TYPE TEXT NULL,
  ADDRESS TEXT NULL,
  CITY TEXT NULL

);

CREATE INDEX idx_encounter_patient ON fact_encounter(PATIENT););

CREATE INDEX idx_encounter_organization ON fact_encounter(ORGANIZATION);

CREATE INDEX idx_encounter_provider ON fact_encounter(PROVIDER);

CREATE INDEX idx_encounter_payer ON fact_encounter(PAYER);

CREATE INDEX idx_encounter_startdate ON fact_encounter(STARTDATE);